version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: jiahongzhang/building-on-ci
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            echo "branch: ${CIRCLE_BRANCH}"
            echo "tag: ${CIRCLE_TAG}"
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then
               docker build -t $IMAGE_NAME:prod .
            else
                docker build -t $IMAGE_NAME:${CIRCLE_BRANCH} .
            fi
            
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived Docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            if [ "${CIRCLE_BRANCH}" == "master" ]
            then
               docker push $IMAGE_NAME:prod
            else
               docker push $IMAGE_NAME:${CIRCLE_BRANCH}
            fi
workflows:
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - develop
                - /rc-.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - develop
                - /rc-.*/
                